// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw278g3ENJSTu_951f9l-PzSu6lMIARzI',
    appId: '1:779977527630:android:f98dd2e694e4dfca1c8e1f',
    messagingSenderId: '779977527630',
    projectId: 'thehalalfoods-e744e',
    databaseURL: 'https://thehalalfoods-e744e-default-rtdb.firebaseio.com',
    storageBucket: 'thehalalfoods-e744e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEx_S-pGCNl5yEeDPbJFtDNlxCSFtbTX8',
    appId: '1:779977527630:ios:879efe44aa45f24d1c8e1f',
    messagingSenderId: '779977527630',
    projectId: 'thehalalfoods-e744e',
    databaseURL: 'https://thehalalfoods-e744e-default-rtdb.firebaseio.com',
    storageBucket: 'thehalalfoods-e744e.appspot.com',
    androidClientId: '779977527630-9b15guu015cn97ob3g15v9a50qflulrr.apps.googleusercontent.com',
    iosClientId: '779977527630-7nkdccfloij5nee19g04sh31hfh6k2q2.apps.googleusercontent.com',
    iosBundleId: 'com.nexteck.thfdriver.ios',
  );

}